name: Create Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  validate-release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract-version.outputs.version }}
      release_notes: ${{ steps.extract-release-notes.outputs.release_notes }}
      is_valid: ${{ steps.validate-conditions.outputs.is_valid }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract version from tag
        id: extract-version
        run: |
          TAG=${GITHUB_REF#refs/tags/v}
          echo "version=$TAG" >> $GITHUB_OUTPUT

      - name: Validate release conditions
        id: validate-conditions
        run: |
          # Check if VERSION file contains the same version as the tag
          VERSION_CONTENT=$(cat VERSION)
          TAG_VERSION=${{ steps.extract-version.outputs.version }}
          
          # Get current date in YYYY-MM-DD format
          CURRENT_DATE=$(date +%Y-%m-%d)
          
          # Check first line of CHANGES file
          FIRST_LINE=$(head -n 1 CHANGES)
          
          if [[ "$VERSION_CONTENT" == "$TAG_VERSION" && "$FIRST_LINE" == *"$CURRENT_DATE"* ]]; then
            echo "All conditions met!"
            echo "is_valid=true" >> $GITHUB_OUTPUT
          else
            echo "Release conditions not met:"
            echo "Tag version: v$TAG_VERSION"
            echo "VERSION file content: $VERSION_CONTENT"
            echo "CHANGES first line date check: $FIRST_LINE should contain $CURRENT_DATE"
            echo "is_valid=false" >> $GITHUB_OUTPUT
            exit 1
          fi

      - name: Extract release notes
        id: extract-release-notes
        run: |
          # Extract the first section of the CHANGES file until the next release entry
          RELEASE_NOTES=$(awk '/^[0-9]{4}-[0-9]{2}-[0-9]{2}/,/^[0-9]{4}-[0-9]{2}-[0-9]{2}/ {if (NR>1 && /^[0-9]{4}-[0-9]{2}-[0-9]{2}/) exit; print}' CHANGES)
          # Escape newlines for GitHub Actions
          RELEASE_NOTES="${RELEASE_NOTES//'%'/'%25'}"
          RELEASE_NOTES="${RELEASE_NOTES//$'\n'/'%0A'}"
          RELEASE_NOTES="${RELEASE_NOTES//$'\r'/'%0D'}"
          echo "release_notes=$RELEASE_NOTES" >> $GITHUB_OUTPUT

  build-and-release:
    needs: validate-release
    if: needs.validate-release.outputs.is_valid == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential autoconf automake

      - name: Build project
        run: |
          ./bootstrap
          ./configure --enable-maintainer-mode
          make
          make clean
          make install
          make dist

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: smokeping-${{ needs.validate-release.outputs.version }}.tar.gz
          name: Release v${{ needs.validate-release.outputs.version }}
          body: ${{ needs.validate-release.outputs.release_notes }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}